### ISSUE TITLE
インストール方法

### ISSUE THREAD

**Issue by alfredplpl** [mattyamonaca/starline#1]
大体の開発者はわかると思いますが、利用者はわからないかもしれません。

```bash
git clone https://github.com/mattyamonaca/starline.git
cd starline
conda create -n starline python=3.10
conda activate starline
conda install pytorch torchvision pytorch-cuda=12.1 -c pytorch -c nvidia
pip install -r requirements.txt
```

のようなやつですね。

**Comment by jonigata** [comment]
issue建てようかと思いましたが、だいたい同じ話なのでこちらで

  % python -m venv env
  % source env/bin/activate
  % pip install -r requirements.txt
  % python app.py

だとtorchがないので、requirements.txtにtorch入れたら動きました

**Comment by mattyamonaca** [comment]
ありがとうございます！READMEに追記させていただきます！

**Comment by mattyamonaca** [comment]
READMEに追記しました！
